### ISSUE TITLE
DBViewer / Create DB Viwer

### ISSUE THREAD

**Issue by jessie129j** [whaleap/during-budget#119]
**간단한 DB 조회 사이트(개발용) 구현하기**

1. 매번 MongoDB 켜서 쿼리해서 데이터 확인하는게 불편하다!
2. 특정 사용자의 데이터만 구분해서 쇽쇽 볼 수 있게 하자!
3. 원클릭으로 도큐먼트 _id 복사해서 API 테스트를 편하게 하자!

**Todo**
- [ ] database 폴더 만들기
- [ ] 특정 사용자 입력하면 관련 데이터 주르륵 띄워주는 페이지 만들기
- [ ] 도큐먼트 클릭하면 _id 복사
