### ISSUE TITLE
Budget / Split budget stage management - total, category

### ISSUE THREAD

**Issue by navynj** [whaleap/during-budget#236]
## Description
- total, budgetCategory를 별도의 slice로 관리하도록 수정 _(from #235)_

## Todos
- [x] total slice & total plan update
- [x] category slice & category plan update
- [x] form -> update total/category/transaction amount (get rid of budgetActions)
- [x] option -> remove transaction
- [x] plan -> update default
