### ISSUE TITLE
Status / Income chart

### ISSUE THREAD

**Issue by earlyoonj** [whaleap/during-budget#34]
# Description:
- Total income chart (amountDoughnut)
- Category icome chart (amountBars)

# Todo:
- [ ] UI: income / expense tab
- [ ] BudgetState: totalIncome, totalExpense
- [ ] BudgetAction: dispatchIncomeAmount, dispatchExpenseAmount

**Comment by earlyoonj** [comment]
**PENDING:** Needs UI design
