### ISSUE TITLE
Payment / Test APIs

### ISSUE THREAD

**Issue by jessie129j** [whaleap/during-budget#489]
# Todo
- [x] 게스트 모드 결제 허용
- [x] 사전 검증, 사후 검증, 웹훅 테스트
- [x] 옵션 조회 API 수정
