### ISSUE TITLE
Auth / Update Authentication

### ISSUE THREAD

**Issue by jessie129j** [whaleap/during-budget#60]
# Todo
- [x] return empty json object when there is nothing to return in resopnse
- [x] auto login & logout
    - [x] send cookie expiry date when user loggs in => no need to do! server returns 403 error if user's session is expired
    - [x] enable to set auto login when user loggs in

**Comment by jessie129j** [comment]
> **인증 로직**
> 
@earlyoonj 지금 서버에서 인증이 이런식으로 진행되는데, 이렇게 되면 클라이언트에서 쿠키의 만료 기간을 따로 받아서 처리할 필요가 없을 것 같아! `GET /users/current` API로 로그인한 유저 정보를 요청하거나 다른 API를 요청했을 때 서버측에서 얘가 로그인한 상태면 정상적인 응답을 보내주고 세션이 삭제된 상태(서버가 봤을 때 로그아웃한 상태)이면 `403 Forbidden`을 반환합니다!
