### ISSUE TITLE
Budgets, Categories, Transactions / Rename fields & considering incomes 

### ISSUE THREAD

**Issue by jessie129j** [whaleap/during-budget#62]
# Todo
**phase 1.** 
- [x] Separate user.categories into user.expenseCategories and user.incomeCategories
- [x] Separate budget.categories into budget.expenseCategories and budget.incomeCategories
- [x] Update Budget APIs

=> #63 

**phase 2.** 
- [x] revert: Merge user.expenseCategories and user.incomeCategories into user.categories
- [x] revert: Merge budget.expenseCategories and budget.incomeCategories into budget.categories
- [x] Update Budget APIs
