### ISSUE TITLE
Budget / Update Budget model and APIs

### ISSUE THREAD

**Issue by jessie129j** [whaleap/during-budget#87]
# Description
Rename field 'budget.cateogires.amount' into 'amountPlaned' and add field 'amountCurrent' and 'amountScheduled'

# Todo
- [x] Rename field 'budget.categories.amount' to 'budget.categories.amountPlanned'
- [x] Update UBudgetCategoryAmountAPI to update 'amountPlanned' instead of 'amount'
- [x] Add field 'amountScheduled' and 'amountCurrent' in 'budget.categories'
- [x] Add fields 'isExpense' and 'isIncome' in transactions
- [x] Update budget fields ('budget.expenseCurrent', 'budget.incomeCurrent', 'budget.expenseScheduled' and 'budget.incomeScheduled') and budget.categories fields )'budget.category.amountCurrent' and 'budget.category.amountScheduled')
    - [x] when transaction is added
    - [x] when transaction is updated
        - [x] amount is updated
        - [x] category is updated
    - [x] when transaction is deleted
